Homework 2
================
Hongjie Liu

Load necessary packages for homework 2.

``` r
library(tidyverse)
library(readxl)
```

## Problem 1

Read and clean the data; retain line, station, name, station latitude /
longitude, routes served, entry, vending, entrance type, and ADA
compliance. Convert the entry variable from character (`YES` vs `NO`) to
a logical variable.

``` r
transit_df_original = read_csv(file = "./data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv")
```

    ## Rows: 1868 Columns: 32
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (22): Division, Line, Station Name, Route1, Route2, Route3, Route4, Rout...
    ## dbl  (8): Station Latitude, Station Longitude, Route8, Route9, Route10, Rout...
    ## lgl  (2): ADA, Free Crossover
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
transit_df = transit_df_original %>% 
  janitor::clean_names() %>% 
  select(line:entry, vending, ada) %>% 
  mutate(entry = recode(entry, "YES" = TRUE, "NO" = FALSE))
```

The variables that the original dataset contains are
`Division, Line, Station Name, Station Latitude, Station Longitude, Route1, Route2, Route3, Route4, Route5, Route6, Route7, Route8, Route9, Route10, Route11, Entrance Type, Entry, Exit Only, Vending, Staffing, Staff Hours, ADA, ADA Notes, Free Crossover, North South Street, East West Street, Corner, Entrance Latitude, Entrance Longitude, Station Location, Entrance Location`.

First, We read the data from the csv file
“NYC_Transit_Subway_Entrance_And_Exit_Data.csv”. Next, we use the
function `janitor::clean_names` to clean up variable names. Last, We use
the functions `recode` and `mutate` to convert the entry variable from
character (`YES` vs `NO`) to a logical variable.

The resulting dataset has 1868 rows and 19 columns.

These data are still not tidy, because the values of the variables
`route8` to `route11` is numeric and should be converted to character,
and route number and route name are not distinct variables.

``` r
stnum = transit_df %>% 
  select(station_name, line) %>% 
  distinct %>% 
  count
```

There are 465 distinct stations.

``` r
stnum_ada = transit_df %>% 
  filter(ada == TRUE) %>% 
  select(station_name, line) %>% 
  distinct %>% 
  count
```

84 stations are ADA compliant.

``` r
total = transit_df %>% 
  filter(vending == "NO") %>% 
  pull(entry)
  
entrynum = sum(total == TRUE)
exitnum = sum(total == FALSE)
```

The ratio of entrances to exits with no vending allow entrance is
1:1.65.

Reformat data so that route number and route name are distinct
variables.

``` r
transit_df$route8 = as.character(transit_df$route8)
transit_df$route9 = as.character(transit_df$route9)
transit_df$route10 = as.character(transit_df$route10)
transit_df$route11 = as.character(transit_df$route11)

transit_df = transit_df %>% 
  pivot_longer(
    route1:route11,
    names_to = "route_number",
    values_to = "route_name") %>% 
  mutate(route_number = str_replace(route_number, "route", ""))
```

``` r
stnum_a = transit_df %>% 
  filter(route_name == "A") %>% 
  select(station_name, line) %>% 
  distinct %>% 
  count

stnum_a_ada = transit_df %>% 
  filter(route_name == "A", ada == TRUE) %>% 
  select(station_name, line) %>% 
  distinct %>% 
  count
```

60 stations serve the A train, of which 17 are ADA compliant.

## Problem 2

Read and clean the Mr. Trash Wheel sheet:

-   specify the sheet in the Excel file and to omit non-data entries
    (rows with notes / figures; columns containing notes) using
    arguments in read_excel
-   use reasonable variable names
-   omit rows that do not include dumpster-specific data
-   round the number of sports balls to the nearest integer and converts
    the result to an integer variable

We assign the dataset to `mrtw_df`.

``` r
mrtw_df = 
  read_excel(
  path = "./data/Trash-Wheel-Collection-Totals-7-2020-2.xlsx",
  sheet = "Mr. Trash Wheel",
  range = "A2:N533"
  ) %>% 
  janitor::clean_names() %>% 
  drop_na(dumpster) %>% 
  mutate(sports_balls = round(sports_balls)) %>% 
  mutate(sports_balls = as.integer(sports_balls))

mrtw_df
```

    ## # A tibble: 453 × 14
    ##    dumpster month  year date                weight_tons volume…¹ plast…² polys…³
    ##       <dbl> <chr> <dbl> <dttm>                    <dbl>    <dbl>   <dbl>   <dbl>
    ##  1        1 May    2014 2014-05-16 00:00:00        4.31       18    1450    1820
    ##  2        2 May    2014 2014-05-16 00:00:00        2.74       13    1120    1030
    ##  3        3 May    2014 2014-05-16 00:00:00        3.45       15    2450    3100
    ##  4        4 May    2014 2014-05-17 00:00:00        3.1        15    2380    2730
    ##  5        5 May    2014 2014-05-17 00:00:00        4.06       18     980     870
    ##  6        6 May    2014 2014-05-20 00:00:00        2.71       13    1430    2140
    ##  7        7 May    2014 2014-05-21 00:00:00        1.91        8     910    1090
    ##  8        8 May    2014 2014-05-28 00:00:00        3.7        16    3580    4310
    ##  9        9 June   2014 2014-06-05 00:00:00        2.52       14    2400    2790
    ## 10       10 June   2014 2014-06-11 00:00:00        3.76       18    1340    1730
    ## # … with 443 more rows, 6 more variables: cigarette_butts <dbl>,
    ## #   glass_bottles <dbl>, grocery_bags <dbl>, chip_bags <dbl>,
    ## #   sports_balls <int>, homes_powered <dbl>, and abbreviated variable names
    ## #   ¹​volume_cubic_yards, ²​plastic_bottles, ³​polystyrene

We use a similar process to import, clean, and organize the data for
Professor Trash Wheel and assign it to `proftw_df`. Next, we combine
this with the Mr. Trash Wheel dataset `mrtw_df` to produce a single tidy
dataset `tw_df`.

``` r
proftw_df = 
  read_excel(
  path = "./data/Trash-Wheel-Collection-Totals-7-2020-2.xlsx",
  sheet = "Professor Trash Wheel",
  range = "A2:N115"
  ) %>% 
  janitor::clean_names() %>% 
  drop_na(dumpster) %>% 
  mutate(sports_balls = round(sports_balls)) %>% 
  mutate(sports_balls = as.integer(sports_balls)) %>% 
  mutate(trash_wheel_type = "Professor Trash Wheel")

mrtw_df = mutate(mrtw_df, trash_wheel_type = "Mr. Trash Wheel")

tw_df = bind_rows(mrtw_df, proftw_df)

tw_df
```

    ## # A tibble: 524 × 15
    ##    dumpster month  year date                weight_tons volume…¹ plast…² polys…³
    ##       <dbl> <chr> <dbl> <dttm>                    <dbl>    <dbl>   <dbl>   <dbl>
    ##  1        1 May    2014 2014-05-16 00:00:00        4.31       18    1450    1820
    ##  2        2 May    2014 2014-05-16 00:00:00        2.74       13    1120    1030
    ##  3        3 May    2014 2014-05-16 00:00:00        3.45       15    2450    3100
    ##  4        4 May    2014 2014-05-17 00:00:00        3.1        15    2380    2730
    ##  5        5 May    2014 2014-05-17 00:00:00        4.06       18     980     870
    ##  6        6 May    2014 2014-05-20 00:00:00        2.71       13    1430    2140
    ##  7        7 May    2014 2014-05-21 00:00:00        1.91        8     910    1090
    ##  8        8 May    2014 2014-05-28 00:00:00        3.7        16    3580    4310
    ##  9        9 June   2014 2014-06-05 00:00:00        2.52       14    2400    2790
    ## 10       10 June   2014 2014-06-11 00:00:00        3.76       18    1340    1730
    ## # … with 514 more rows, 7 more variables: cigarette_butts <dbl>,
    ## #   glass_bottles <dbl>, grocery_bags <dbl>, chip_bags <dbl>,
    ## #   sports_balls <int>, homes_powered <dbl>, trash_wheel_type <chr>, and
    ## #   abbreviated variable names ¹​volume_cubic_yards, ²​plastic_bottles,
    ## #   ³​polystyrene

Here is a description of the resulting dataset `tw_df`:

-   The variables of the dataset are
    `dumpster, month, year, date, weight_tons, volume_cubic_yards, plastic_bottles, polystyrene, cigarette_butts, glass_bottles, grocery_bags, chip_bags, sports_balls, homes_powered, trash_wheel_type`.
-   Here are some values of several key variables of the dataset: some
    values of the variable `weight_tons` are `4.31, 2.74, 3.45`. Some
    values of the variable `plastic_bottles` are `1450, 1120, 2450`.
-   It has 524 rows (number of observations) and 15 columns.

For available data, we have:

-   Professor Trash Wheel collected 135.5 tons of trash.
-   Mr. Trash Wheel collected 856 sports balls in 2020.
